name: Eleventy Build
on: 
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Use node.js current
        uses: actions/setup-node@v3
        with: 
          node-version: current
        
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          publish_dir: public
          github_token: ${{secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages